
compare_product_index:
    pattern:  /compare_product/index
    defaults: { _controller: LoveThatFitSiteBundle:CompareProduct:index}

compare_product_list:
    pattern:  /compare_product/list
    defaults: { _controller: LoveThatFitSiteBundle:CompareProduct:list}

compare_product_add:
    pattern:  /compare_product/add/{item_id}
    defaults: { _controller: LoveThatFitSiteBundle:CompareProduct:add}

compare_product_remove:
    pattern:  /compare_product/remove/{product_id}
    defaults: { _controller: LoveThatFitSiteBundle:CompareProduct:remove}
