parameters:
#    love_that_fit_retailer_admin.example.class: LoveThatFit\RetailerAdminBundle\Example

services:
#    love_that_fit_retailer_admin.example:
#        class: %love_that_fit_retailer_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
