si_index:
    pattern:  /service_interface/index
    defaults: { _controller: LoveThatFitWebServiceBundle:ServiceInterface:index}

si_hit:
    pattern:  /service_interface/hit
    defaults: { _controller: LoveThatFitWebServiceBundle:ServiceInterface:hit}

si_user_detail:
    pattern:  /service_interface/user_detail/{email}
    defaults: { _controller: LoveThatFitWebServiceBundle:ServiceInterface:userDetail}

si_foo:
    pattern:  /service_interface/foo
    defaults: { _controller: LoveThatFitWebServiceBundle:ServiceInterface:foo}

si_bar:
    pattern:  /service_interface/bar
    defaults: { _controller: LoveThatFitWebServiceBundle:ServiceInterface:bar}
