si_index:
    pattern:  /service_interface/index
    defaults: { _controller: LoveThatFitWebServiceBundle:ServiceInterface:index}

si_hit:
    pattern:  /service_interface/hit
    defaults: { _controller: LoveThatFitWebServiceBundle:ServiceInterface:hit}
