parameters:
#    love_that_fit_product_intake.example.class: LoveThatFit\ProductIntakeBundle\Example

services:
#    love_that_fit_product_intake.example:
#        class: %love_that_fit_product_intake.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    admin.fit_model_measurement:
            class: LoveThatFit\ProductIntakeBundle\Entity\FitModelMeasurementHelper
            arguments:
                dispatcher: "@event_dispatcher"
                em: "@doctrine.orm.entity_manager"
                class: LoveThatFit\ProductIntakeBundle\Entity\FitModelMeasurement
                container: "@service_container"