parameters:
#    love_that_fit_product_intake.example.class: LoveThatFit\ProductIntakeBundle\Example

services:
#    love_that_fit_product_intake.example:
#        class: %love_that_fit_product_intake.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
