
app_scopes:
  [read_products, write_themes, write_content, read_customers, read_orders]
  
masked_marker:
  bust: [24,60]
  chest: [24,60]  
  shoulder_across_front: [16,2]
  waist: [27,57]
  hip: [29,55]
  inseam: [42,38]
  thigh_right: [30,41]
  thigh_left: [43,54]
  shoulder_length_right: [15,36]
  shoulder_length_left: [3,48]
  bicep_left: [1,62]
  bicep_right: [17,22]
  wrist_left: [0,63]
  wrist_right: [18,21]
  knee_right: [31,40]
  knee_left: [44,53]
  calf_right: [32,39]
  calf_left: [45,52]
  ankle_right: [34,38]
  ankle_left: [46,50]
    
    