
masked_marker:
  bust: 
    axis: x
    type: single
    segments: 
      s1:  
        a: 24
        b: 60
    
  chest:  
    axis: x
    type: single
    segments: 
      s1: 
        a: 24
        b: 60    
  
  shoulder_across_front: 
    axis: x 
    type: single
    segments: 
      s1:
        a: 16
        b: 2    
  
  waist: 
    axis: x 
    type: single
    segments: 
      s1:
        a: 27
        b: 57
    
  hip: 
    axis: x 
    type: single 
    segments: 
      s1: 
        a: 29
        b: 55
    
  inseam: 
    axis: y
    type: single
    segments: 
      s1:
        a: 42
        b: 38
    
  thigh: 
    axis: x 
    type: pair
    segments: 
      s1:
        a: 30
        b: 41
      s2: 
        a: 43
        b: 54
    
  shoulder_length: 
    axis: y 
    type: pair
    segments: 
      s1:
        a: 15
        b: 36
      s2:
        a: 3
        b: 48
    
  bicep:  
    axis: x 
    type: pair 
    segments: 
      s1:
        a: 17
        b: 22
      s2:
        a: 1
        b: 62
    
  wrist:  
    axis: x 
    type: pair 
    segments: 
      s1:
        a: 0
        b: 63
      s2:
        a: 18
        b: 21
  
  knee: 
    axis: x 
    type: pair
    segments: 
      s1:
        a: 31
        b: 40
      s2:
        a: 44
        b: 53
    
  calf: 
    axis: x 
    type: pair
    segments: 
      s1:
        a: 32
        b: 39
      s2:
        a: 45
        b: 52
    
  ankle:  
    axis: x 
    type: pair
    segments: 
      s1:
        a: 34
        b: 38
      s2:
        a: 46
        b: 50
        
masked_marker1:
  bust: [24,60]
  chest: [24,60]  
  shoulder_across_front: [16,2]
  waist: [27,57]
  hip: [29,55]
  inseam: [42,38]
  thigh_right: [30,41]
  thigh_left: [43,54]
  shoulder_length_right: [15,36]
  shoulder_length_left: [3,48]
  bicep_left: [1,62]
  bicep_right: [17,22]
  wrist_left: [0,63]
  wrist_right: [18,21]
  knee_right: [31,40]
  knee_left: [44,53]
  calf_right: [32,39]
  calf_left: [45,52]
  ankle_right: [34,38]
  ankle_left: [46,50]
    
    