
masked_marker:
  bust: [x, single, [24,60]]
  chest:  [x, single, [24,60]]
  shoulder_across_front: [x, single, [16,2]]
  waist: [x, single, [27,57]]
  hip: [x, single, [29,55]]
  inseam: [y, single, [42,38]]
  thigh: [x, pair, [30,41],[43,54]]
  shoulder_length: [y, pair, [15,36],[3,48]]
  bicep:  [x, pair, [17,22],[1,62]]
  wrist:  [x, pair, [0,63],[18,21]]
  knee: [x, pair, [31,40],[44,53]]
  calf: [x, pair, [32,39],[45,52]]
  ankle:  [x, pair, [34,38],[46,50]]
  
masked_marker3:
  bust: [[[24,60]],x,single]
  chest:  [[[24,60]],x,single]  
  shoulder_across_front: [[[16,2]],x,single]
  waist: [[[27,57]],x,single]
  hip: [[[29,55]],x,single]
  inseam: [[[42,38]],y,single]
  thigh: [[[30,41],[43,54]],x,pair]
  shoulder_length: [[[15,36],[3,48]],y,pair]
  bicep:  [[[17,22],[1,62]],x,pair]
  wrist:  [[[0,63],[18,21]],x,pair]
  knee: [[[31,40],[44,53]],x,pair]
  calf: [[[32,39],[45,52]],x,pair]
  ankle:  [[[34,38],[46,50]],x,pair]
    

masked_marker2:
  bust: [24,60, axis:x, type:single]
  chest: [24,60, axis:x, type:single]  
  shoulder_across_front: [16,2, axis:x, type:single]
  waist: [27,57, axis:x, type:single]
  hip: [29,55, axis:x, type:single]
  inseam: [42,38, axis:y, type:single]
  thigh: [30,41, axis:x, type:single]
  thigh_right: [30,41, axis:x, type:pair]
  thigh_left: [43,54, axis:x, type:pair]
  shoulder_length: [15,36, axis:y, type:single]
  shoulder_length_right: [15,36, axis:y, type:pair]
  shoulder_length_left: [3,48, axis:y, type:pair]
  bicep: [1,62, axis:x, type:single]
  bicep_left: [1,62, axis:x, type:pair]
  bicep_right: [17,22, axis:x, type:pair]
  wrist: [0,63, axis:x, type:single]
  wrist_left: [0,63, axis:x, type:pair]
  wrist_right: [18,21, axis:x, type:pair]
  knee: [31,40, axis:x, type:single]
  knee_right: [31,40, axis:x, type:pair]
  knee_left: [44,53, axis:x, type:pair]
  calf: [32,39, axis:x, type:single]
  calf_right: [32,39, axis:x, type:pair]
  calf_left: [45,52, axis:x, type:pair]
  ankle: [34,38, axis:x, type:single]
  ankle_right: [34,38, axis:x, type:pair]
  ankle_left: [46,50, axis:x, type:pair]
    
        
masked_marker1:
  bust: [24,60]
  chest: [24,60]  
  shoulder_across_front: [16,2]
  waist: [27,57]
  hip: [29,55]
  inseam: [42,38]
  thigh_right: [30,41]
  thigh_left: [43,54]
  shoulder_length_right: [15,36]
  shoulder_length_left: [3,48]
  bicep_left: [1,62]
  bicep_right: [17,22]
  wrist_left: [0,63]
  wrist_right: [18,21]
  knee_right: [31,40]
  knee_left: [44,53]
  calf_right: [32,39]
  calf_left: [45,52]
  ankle_right: [34,38]
  ankle_left: [46,50]
    
    