1:
  faq_type: fitting_room
  question: Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
  answer: Vivamus tristique tempor venenatis. Sed felis purus, auctor maximus maximus sit amet, pretium eu leo
  tags: selfie full height, algorithm, table, height, weight, bra size, body shape, accuracy, accurate
  index: 1
2:
  faq_type: social_sharing
  question: Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
  answer: Vivamus tristique tempor venenatis. Sed felis purus, auctor maximus maximus sit amet, pretium eu leo
  tags: selfie full height, algorithm, table, height, weight, bra size, body shape, accuracy, accurate
  index: 2
3:
  faq_type: measurement
  question: Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
  answer: Vivamus tristique tempor venenatis. Sed felis purus, auctor maximus maximus sit amet, pretium eu leo
  tags: selfie full height, algorithm, table, height, weight, bra size, body shape, accuracy, accurate
  index: 3
    
  