<?php

namespace LoveThatFit\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserItemFavHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserItemFavHistoryRepository extends EntityRepository
{
    public function find($id){
        echo $id;
        exit;
    }


    public function findUserItemAllFavHistory($user, $product, $productItem)
    {
        $total_record = $this->getEntityManager()
            ->createQuery("SELECT ut FROM LoveThatFitSiteBundle:UserItemFavHistory ut
     WHERE
     ut.user=:user_id
     AND ut.productitem=:product_item_id
     AND
     ut.product=:product_id"
            )->setParameters(array('user_id' => $user, 'product_item_id' => $productItem, 'product_id' => $product));
        try {
            return $total_record->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findUserFavProdcuts($user)
    {
        $total_record = $this->getEntityManager()
            ->createQuery("SELECT ut FROM LoveThatFitSiteBundle:UserItemFavHistory ut
     WHERE
     ut.user=:user_id"
            )->setParameters(array('user_id' => $user));
        try {
            return $total_record->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
