<?php

namespace LoveThatFit\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserItemTryHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFittingRoomItemRepository extends EntityRepository
{
    public function findUserFittingRommItem($user,$product,$productItem)
	 {
	  $total_record= $this->getEntityManager()
                        ->createQuery("SELECT ut FROM LoveThatFitSiteBundle:UserFittingRoomItem ut
     WHERE
     ut.user=:user_id
     AND ut.productitem=:product_item_id
     "
              )->setParameters(array('user_id' =>$user,'product_item_id'=>$productItem));
 	  try 
	    {
		 return $total_record->getResult();
		}
                    catch (\Doctrine\ORM\NoResultException $e) 
		 {
		   return null;
		 }						
	  }  
          
          
          
}
