hello:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Hello:index }
    
acme_intro:
    pattern:  /acme/intro/
    defaults: { _controller: AcmeHelloBundle:Intro:index }    
    
    