<?php

namespace LoveThatFit\ExternalSiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RetailerOrderItemTrackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetailerOrderItemTrackRepository extends EntityRepository
{
}
