<?php

namespace LoveThatFit\ExternalSiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RetailerOrderTrackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetailerOrderTrackRepository extends EntityRepository
{
}
