## users routes start ##
support_users:
    pattern:  /support/users
    defaults: { _controller: LoveThatFitSupportBundle:User:index}

support_users_paginate:
    pattern:  /support/users/paginate
    defaults: { _controller: LoveThatFitSupportBundle:User:paginate}
## users routes start ##

#show user detail
support_user_detail_show:
    pattern:  /support/user/{id}/show
    defaults: { _controller: LoveThatFitSupportBundle:User:show }