<?php

namespace LoveThatFit\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MeasurementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeasurementRepository extends EntityRepository
{
    
    public function findOneByUserId($id)
{
    $query = $this->getEntityManager()
        ->createQuery('
            SELECT m FROM LoveThatFitUserBundle:Measurement m
            JOIN m.user u
            WHERE u.id = :id'
        )->setParameter('id', $id);

    try {
        return $query->getSingleResult();
    } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    }
}
}
