<?php

namespace LoveThatFit\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PushNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PushNotificationRepository extends EntityRepository
{
#-------------------- Find By User Id-----------------------------------------#
 public function findByUserId($userId) {
  $query = $this->getEntityManager()
             ->createQuery("SELECT pn FROM LoveThatFitUserBundle:PushNotification pn   
                           WHERE pn.userId = :userId")
             ->setParameters(array('userId' => $userId));
   try {
         return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
