<?php

namespace LoveThatFit\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * SelfieshareFeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SelfieshareFeedbackRepository extends EntityRepository
{
    public function getCountByShareId($share_id)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        $query->select('COUNT(s)')->from('LoveThatFitUserBundle:SelfieshareFeedback', 's')
            ->andWhere('s.selfieshare =:share_id')
            ->setParameter('share_id', $share_id);
        $count = $query->getQuery()->getSingleScalarResult();
        return $count;
    }
}
