<?php

namespace LoveThatFit\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserParentChildLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserParentChildLinkRepository extends EntityRepository
{
    public function findByUser($user) {
        $record = $this->getEntityManager()
                        ->createQuery("SELECT u,up FROM LoveThatFitUserBundle:UserParentChildLink u     
                                       JOIN u.child up
                                       WHERE u.child=:child_id")
                        ->setParameters(array('child_id' => $user));
        try {
            return $record->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    public function findUserByParentEmail($email)
    {
         $record = $this->getEntityManager()
                        ->createQuery("SELECT u FROM LoveThatFitUserBundle:UserParentChildLink u                                            
                                       WHERE u.email=:email")
                        ->setParameters(array('email' => $email));
        try {
            return $record->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
}
