<?php

namespace LoveThatFit\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserMarkerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserImageSpecRepository extends EntityRepository
{

  #--------------- Find all base on user id ---------------------------#
  public function findByUser($user){
	$query = $this->getEntityManager()
	  ->createQuery("
     SELECT ui FROM LoveThatFitUserBundle:UserImageSpec ui
     WHERE  ui.user =:user"
	  )->setParameters(array('user' => $user));
	try {
	  return $query->getArrayResult();
	} catch (\Doctrine\ORM\NoResultException $e) {
	  return null;
	}
  }
    
    
}
