<?php

namespace LoveThatFit\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserMarkerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMarkerRepository extends EntityRepository
{
   
    public function findMarkerByUser($user)
    {
        $record = $this->getEntityManager()
                        ->createQuery("SELECT m FROM LoveThatFitUserBundle:UserMarker m                                           
                                       WHERE m.user=:user_id")
                        ->setParameters(array('user_id' => $user));
        try {
            return $record->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    
}
