<?php

namespace LoveThatFit\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserAppAccessLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAppAccessLogRepository extends EntityRepository
{
  public function findOneByUserId($user) {
	$record = $this->getEntityManager()
	  ->createQuery(
		"SELECT count(c.updated_count) as valCount,c.id,c.updated_count
		 FROM LoveThatFitUserBundle:UserAppAccessLog c WHERE c.user=:user
		 ")->setParameter('user',$user);
	try {
	  return $record->getSingleResult();
	} catch (\Doctrine\ORM\NoResultException $e) {
	  return null;
	}
  }
}
