<?php

namespace LoveThatFit\CartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserAddressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAddressesRepository extends EntityRepository
{
  public function findAddressByUserId($user,$is_billing) {
	$record = $this->getEntityManager()
	  ->createQuery(
		"SELECT a.id,a.address1
		 FROM LoveThatFitCartBundle:UserAddresses a

		 where a.user=:user and a.is_billing=:is_billing
		 ")->setParameter('user',$user)
	  ->setParameter('is_billing', $is_billing);

	try {
	  return $record->getArrayResult();
	} catch (\Doctrine\ORM\NoResultException $e) {
	  return null;
	}
  }
}
