<?php

namespace LoveThatFit\CartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserOrderRepository extends EntityRepository
{
  public function findOneByUserAddress($user) {
	$record = $this->getEntityManager()
	  ->createQuery(
		"SELECT uo.id,uo.shipping_first_name,uo.shipping_last_name,
		 uo.shipping_address1,uo.shipping_city,uo.shipping_country,uo.shipping_postcode,uo.shipping_state
		 FROM LoveThatFitCartBundle:UserOrder uo where  uo.user=:user
		 ")->setParameter('user',$user)->setMaxResults(1);
	//echo $record->getSQL();die;
	//print_r($record);
	//die;
	try {
	  return $record->getSingleResult();
	} catch (\Doctrine\ORM\NoResultException $e) {
	  return null;
	}
  }
}
