<?php

namespace LoveThatFit\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends EntityRepository
{
	
/*-----------------------------------------------------------------
Written:Raghib
Description: Find all product with limit and sort 
param:limit, page_number,limit,sort	 
------------------------------------------------------------------*/
	 public function findAllBanner($page_number = 0, $limit = 0 ,$sort='id'  ) {
				   
             if ($page_number <= 0 || $limit <= 0) {
            $query = $this->getEntityManager()
                    ->createQuery('SELECT c FROM LoveThatFitAdminBundle:Banner c ORDER BY c.' . $sort . ' ASC');
        } else {
            $query = $this->getEntityManager()
                    ->createQuery('SELECT c FROM LoveThatFitAdminBundle:Banner c ORDER BY c.' . $sort . ' ASC')
                    ->setFirstResult($limit * ($page_number - 1))
                    ->setMaxResults($limit);
        }
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
   
  /*-----End Of Function-----------------*/
	
	 /*-----------------------------------------------------------------
      Written:Raghib
	  Description:Count all Records
	  param:limit:
	 ------------------------------------------------------------------*/ 
     public function countAllRecord()
	 {
	  $total_record= $this->getEntityManager()
	   ->createQuery('SELECT c FROM LoveThatFitAdminBundle:Banner c');
	  try 
	    {
		 return $total_record->getResult();
		}
		catch (\Doctrine\ORM\NoResultException $e) 
		 {
		   return null;
		 }						
	  }   
	 
	public function findBannerBy($name,$catid) {
        $total_record = $this->getEntityManager()
        ->createQuery("SELECT ct FROM LoveThatFitAdminBundle:Banner ct
        WHERE
        ct.name = :name
        AND ct.cat_id=:catid"
                        )->setParameters(array('name' => $name, 'catid' => $catid));
        try {
            return $total_record->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    
    public function listAllBanner($page_number = 0, $limit = 0, $sort = 'id') {


        if ($page_number <= 0 || $limit <= 0) {
            $query = $this->getEntityManager()
                    ->createQuery('SELECT c FROM LoveThatFitAdminBundle:Banner c ORDER BY c.' . $sort . ' ASC');
        } else {
            $query = $this->getEntityManager()
                    ->createQuery('SELECT c FROM LoveThatFitAdminBundle:Banner c ORDER BY c.' . $sort . ' ASC')
                    ->setFirstResult($limit * ($page_number - 1))
                    ->setMaxResults($limit);
        }
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return "null";
        }
    }

    public function findAllAvailableRecords()
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT c FROM LoveThatFitAdminBundle:Banner c where c.disabled=0  order by c.id,c.sorting, c.name');
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
        
    public function findAllRecord()
    {
      $query = $this->getEntityManager()
                ->createQuery('SELECT c FROM LoveThatFitAdminBundle:Banner c order by c.id,c.sorting, c.name');
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    #-----------------------------------------------------------------------------

    public function findStatisticsBy($catid)
    {
     $query = $this->getEntityManager()
        ->createQuery("SELECT ct FROM LoveThatFitAdminBundle:Banner ct
        WHERE        
        ct.cat_id=:catid"
                        )
             ->setParameter('catid',$catid);
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    
  #-------------Find All Banner for Web Service -----#
    public function findAllBanners($displayscreen='') {

        if($displayscreen!=''){
            $query = $this->getEntityManager()
                ->createQuery("SELECT c.id as id, c.parent_id as parent_id, c.name as title,
                c.image as banner_image ,c.image_position as image_position,
                c.banner_type as banner_type ,c.display_screen as display_screen,
                c.cat_id as targeted_cat_id ,c.description as description,
                c.sorting as sorting ,c.price_min as price_min,
                c.price_max as price_max , 'banner' AS type
                FROM LoveThatFitAdminBundle:Banner c
                LEFT JOIN c.children d
                WHERE c.disabled=0 AND c.display_screen = :display_screen
                GROUP BY c.id
                order by c.sorting, c.updated_at desc")
                ->setParameters(array('display_screen' => $displayscreen));
        }else{
            $query = $this->getEntityManager()
                ->createQuery("SELECT c.id as id, c.parent_id as parent_id, c.name as title,
                c.image as banner_image ,c.image_position as image_position,
                c.banner_type as banner_type ,c.display_screen as display_screen,
                c.cat_id as targeted_cat_id ,c.description as description,
                c.sorting as sorting ,c.price_min as price_min,
                c.price_max as price_max , 'banner' AS type
                FROM LoveThatFitAdminBundle:Banner c
                LEFT JOIN c.children d
                WHERE c.disabled=0
                GROUP BY c.id
                order by c.sorting, c.updated_at desc");
        }


        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    
    public function findOneByName($name) {
        $record = $this->getEntityManager()
                        ->createQuery("SELECT c FROM LoveThatFitAdminBundle:Banner c
                                WHERE c.name = :name")
                        ->setParameters(array('name' => $name));
        try {
            return $record->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findBannerByName($name) {
        $record = $this->getEntityManager()
                        ->createQuery("SELECT c FROM LoveThatFitAdminBundle:Banner c
                                WHERE c.name = :name")
                        ->setParameters(array('name' =>$name));
        try {
            return $record->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
     public function findOneByCatIdName($cat_id, $name) {
        $record = $this->getEntityManager()
                        ->createQuery("SELECT c FROM LoveThatFitAdminBundle:Banner c
                                WHERE c.name = :name AND c.cat_id = :catid")
                        ->setParameters(array('name' =>$name, 'catid' => $cat_id));
        try {
            return $record->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    public function findBannerByProduct($product)
  {
      $query = $this->getEntityManager()
                        ->createQuery("
     SELECT b FROM LoveThatFitAdminBundle:Banner b
     WHERE
     b.id=:id     
    "  )->setParameters(array('id' => $product)) ;
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
  }
  
  
  
  
  public function findBannerByCatId($cat_id)
  {
      $query = $this->getEntityManager()
                        ->createQuery("
     SELECT b FROM LoveThatFitAdminBundle:Banner b
     WHERE
     b.cat_id=:catid
    "  )->setParameters(array('catid' => $cat_id)) ;
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
  }
  
#------------------------------------------------------------------------------#  
  public function getRecordsCountWithCurrentBannerLimit($banner){
     $query = $this->getEntityManager()
                    ->createQuery("SELECT count(c.id) as id  FROM LoveThatFitAdminBundle:Banner c WHERE c.id <=:banner")
                   ->setParameters(array('banner' => $banner));
                     try {
                     return $query->getResult();
                } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
                }
  }  
 #--------------Find Banner By Gender---------------------------------#
  public function findByCatId($cat_id){
       $query = $this->getEntityManager()
                        ->createQuery("
     SELECT ct.id as id,ct.name as name FROM LoveThatFitAdminBundle:Banner ct
     WHERE
     ct.cat_id=:catid
    "  )->setParameters(array('catid' => $cat_id)) ;
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
      
  }
#--------------Find Banner By ID---------------------------------#
  public function findById($id){
       $query = $this->getEntityManager()
                        ->createQuery("
     SELECT ct.name as name,ct.cat_id as target FROM LoveThatFitAdminBundle:Banner ct
     WHERE
     ct.id=:id     
    "  )->setParameters(array('id' => $id)) ;
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
      
  }


#--------------Find Banner with Category Name By ID--  -------------------------------#
    public function findWithCategoryName($id){

        $query = $this->getEntityManager()->createQueryBuilder();
        $query->select('
                    e.id,
                    e.name,
                    e.display_screen,
                    e.cat_id,
                    f.name as cat_name,
                    e.image,
                    e.image_position,
                    e.banner_type,
                    e.description,
                    e.sorting,
                    e.price_min,
                    e.price_max,
                    e.disabled,
                    e.created_at'
                )
            ->from('LoveThatFitAdminBundle:Banner', 'e')
            ->Join('LoveThatFitAdminBundle:Categories','f')
            ->where('e.cat_id = f.id')
            ->andWhere('e.id = :id')
            ->setParameter('id', $id);


        try {

            return $query->getQuery()->setMaxResults(1)->getResult();//$query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }

#--------------Find Banner By ID---------------------------------#
    public function search(
        $data,
        $page = 0,
        $max = NULL,
        $order,
        $getResult = true
    )
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        $search = isset($data['query']) && $data['query']?$data['query']:null;
        $query
            ->select('
            e.id,
            e.name,
            e.display_screen,
            e.cat_id,
            f.name as cat_name,
            e.image,
            e.disabled,
            e.created_at'
            )
            ->from('LoveThatFitAdminBundle:Banner', 'e')
            ->leftJoin('LoveThatFitAdminBundle:Categories','f')
            ->where('f.id = e.cat_id');
        if ($search) {
            $query
                ->andWhere('e.name like :search')
                ->setParameter('search', "%".$search."%");
        }
        if (is_array($order)) {
            $orderByColumn    = $order[0]['column'];
            $orderByDirection = $order[0]['dir'];
            $query->OrderBy("e.id", $orderByDirection);
        }

        if ($max) {
            $preparedQuery = $query->getQuery()
                ->setMaxResults($max)
                ->setFirstResult(($page) * $max);
        } else {
            $preparedQuery = $query->getQuery();
        }
        return $getResult?$preparedQuery->getResult():$preparedQuery;
    }

#--------------Add Parent Id in Child category ---------------------------------#
    public function addParentIdInChild($id, $parent){

        $record = $this->getEntityManager()
            ->createQuery("UPDATE LoveThatFitAdminBundle:Banner c
                            Set c.parent_id = :parent_id
                                WHERE c.id = :id")
            ->setParameters(array('parent_id' => $parent,'id' => $id));
        try {
            return $record->execute();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }


    #--------------Find Categories By ID---------------------------------#
    public function findAllBannerDropdown($parent_id = 0) {

        $query = $this->getEntityManager()
            ->createQuery("SELECT c.id as id, c.name as name, c.parent_id as parent_id, c.banner_type as banner_type
            FROM LoveThatFitAdminBundle:Banner c
            WHERE c.disabled=0 and c.parent_id is null ORDER BY c.id asc ");

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
