<?php

namespace LoveThatFit\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColorRepository extends EntityRepository
{
     public function getAllColors() {
        $query = $this->getEntityManager()
                ->createQuery('SELECT c FROM LoveThatFitAdminBundle:Color c');
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
