<?php

namespace LoveThatFit\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronNotificationRepository extends EntityRepository {
    
	public function findByCronTypes($cronType)
    {
    	return $this->getEntityManager()
    		->createQueryBuilder()
    		->select('c')
    		->from('LoveThatFitAdminBundle:CronNotification', 'c')
    		->where('c.cron_type=:cronType')
            ->setParameter('cronType', $cronType)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
