<?php

namespace LoveThatFit\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClothingTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventManagementRepository extends EntityRepository
{
	
/*-----------------------------------------------------------------
Written:Suresh
Description: Find all product with limit and sort 
param:limit, page_number,limit,sort	 
------------------------------------------------------------------*/
	
  #-------------Find All Clothing type for Web Service -----#
  public function findAllRecord()
  {
    $query = $this->getEntityManager()
      ->createQuery('SELECT e.id, e.event_name 
        FROM LoveThatFitAdminBundle:EventManagement e 
        where e.disabled = 1
        order by e.id Desc
    ');
    try {
      return $query->getResult();
    } catch (\Doctrine\ORM\NoResultException $e) {
      return null;
    }
  }
    
  public function findClothingTypeByName($name) {
      $record = $this->getEntityManager()
                      ->createQuery("SELECT c FROM LoveThatFitAdminBundle:ClothingType c    
                              WHERE c.name = :name")
                      ->setParameters(array('name' =>$name));
      try {
          return $record->getResult();
      } catch (\Doctrine\ORM\NoResultException $e) {
          return null;
      }
  }
  #--------------Find Clothing Type By ID---------------------------------#
  public function findById($id){
       $query = $this->getEntityManager()
                        ->createQuery("
     SELECT ct.name as name,ct.target as target FROM LoveThatFitAdminBundle:ClothingType ct     
     WHERE
     ct.id=:id     
    "  )->setParameters(array('id' => $id)) ;
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
      
  }
}
