<?php

namespace LoveThatFit\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FNFUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FNFUserRepository extends EntityRepository
{
    public function getApplicableUserForDiscount( $user_id )
    {
        $query = $this->getEntityManager()
            ->createQuery("select fnf from LoveThatFitAdminBundle:FNFUser fnf
                            JOIN fnf.users u
                            LEFT JOIN u.user_orders o
                            WHERE
                            u.id = :id AND 
                            fnf.is_available = 1
                            and o.discount_amount = 0
                            ")
            ->setParameters(array('id' => $user_id ));

        try {
            /*echo $query->getSQL(); die;
            return $query->getResult();*/
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {

            $query = $this->getEntityManager()
                ->createQuery("select fnf from LoveThatFitAdminBundle:FNFUser fnf
                            JOIN fnf.users u
                            LEFT JOIN u.user_orders o
                            WHERE
                            u.id = :id AND 
                            fnf.is_available = 1
                            ")
                ->setParameters(array('id' => $user_id ));
            try{
                return $query->getSingleResult();
            }catch (\Doctrine\ORM\NoResultException $e){
                return null;
            }

        }

    }
}
