<?php

namespace LoveThatFit\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;

/**
 * ProductImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductImageRepository extends EntityRepository
{
	
/*-----------------------------------------------------------------
Written:Asif Raza
Description: Find all product Images table recods by Product ID 
------------------------------------------------------------------*/
	 public function findByProductId($productId) {
             
	   $query = $this->getEntityManager()->createQuery("
            SELECT pi.id as productImageId,p.id as ProductId, pi.image_title as ImageTtle, pi.image as ProductImage, pi.image_sort as ImageSort 
            FROM LoveThatFitAdminBundle:ProductImage pi
            JOIN pi.product p            
            WHERE p.id=:productId ORDER BY pi.image_sort ASC" 
                                )->setParameters(array('productId' => $productId));
                return $query->getResult();
        try {
                    
                } catch (\Doctrine\ORM\NoResultException $e) {
                    return null;
                }
    }
   
  /*-----End Of Function-----------------*/

}
