<?php

namespace LoveThatFit\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findByGenderBrand($gender, $brand_id)
    {
        $query = $this->getEntityManager()
        ->createQuery('
            SELECT p FROM LoveThatFitAdminBundle:Product p 
            JOIN p.brand b
            WHERE b.id = :id
            AND p.gender = :gender'
        )->setParameters(array('id'=> $brand_id,'gender'=>$gender));

    try {
        return $query->getResult();
    } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    }
    
    }
    
    
    public function findByGenderClothingType($gender, $clothing_type_id)
    {
        $query = $this->getEntityManager()
        ->createQuery('
            SELECT p FROM LoveThatFitAdminBundle:Product p 
            JOIN p.clothing_type ct
            WHERE ct.id = :clothing_type_id
            AND p.gender = :gender'
        )->setParameters(array('clothing_type_id'=> $clothing_type_id,'gender'=>$gender));

    try {
        return $query->getResult();
    } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    }
    
    }
    
    public function findSampleClothingTypeGender($gender)
    {
        $query = $this->getEntityManager()
        ->createQuery('
            SELECT p FROM LoveThatFitAdminBundle:Product p 
            JOIN p.clothing_type ct
            WHERE p.gender = :gender'
        )->setParameter('gender', $gender);

    try {
        return $query->getResult();
    } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    }
    
    }
    
}
