<?php

namespace LoveThatFit\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductColorViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductColorViewRepository extends EntityRepository {

    public function findProductColorViewByColor($color_id) {
            $query = $this->getEntityManager()
                        ->createQuery("
     SELECT pcv FROM LoveThatFitAdminBundle:ProductColorView pcv          
      WHERE
      pcv.product_color = :color_id"                         
                        )->setParameters(array('color_id' => $color_id)) ;
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}