<?php

namespace LoveThatFit\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductItemRepository extends EntityRepository
{
    public function findProductItemByUser($user_id) {
            $query = $this->getEntityManager()
                            ->createQuery('
            SELECT p,c,u FROM LoveThatFitAdminBundle:ProductItem p 
            JOIN p.users_product_items u
            JOIN u.ltf_users c
            WHERE u.user_id = :user_id'
                            )->setParameters(array('user_id' => $user_id));
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
