<?php

namespace LoveThatFit\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RetailerSiteUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetailerSiteUserRepository extends EntityRepository
{
    public function findSiteUserByUserId($user_id){
         $query = $this->getEntityManager()
                    ->createQuery("SELECT rs FROM LoveThatFitAdminBundle:RetailerSiteUser rs
                    WHERE rs.user =:user_id")
                   ->setParameters(array('user_id' => $user_id));
                     try {
                     return $query->getResult();
                } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
                }
        
    }
}
