<?php

namespace LoveThatFit\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RetailerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetailerUserRepository extends EntityRepository
{
    public function getRetaielerUserByRetailer($retailer)
    {
        $query = $this->getEntityManager()
                    ->createQuery("SELECT r,ru FROM LoveThatFitAdminBundle:RetailerUser ru
                    JOIN ru.retailer r   
                    WHERE ru.retailer =:retailer")
                   ->setParameters(array('retailer' => $retailer));
                     try {
                     return $query->getResult();
                } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
                }
    }
    
    public function findOneByName($name) {
        $record = $this->getEntityManager()
                        ->createQuery("SELECT ru FROM LoveThatFitAdminBundle:RetailerUser ru                                 
                             WHERE ru.username = :name")
                        ->setParameters(array('name' => $name));
        try {
            return $record->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
   public function isDuplicateEmail($id, $email)
   {
       $record = $this->getEntityManager()
                        ->createQuery("SELECT ru FROM LoveThatFitAdminBundle:RetailerUser ru                                 
                             WHERE ru.email = :email")
                        ->setParameters(array('email' => $email));
        try {
            return $record->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
   }
   
   public function getRetailerNameByRetailerUser($retailer)
    {
        $query = $this->getEntityManager()
                    ->createQuery("SELECT r,ru FROM LoveThatFitAdminBundle:Retailer r
                    JOIN r.retailer_users ru   
                        WHERE ru.id =:id")
                   ->setParameters(array('id' => $retailer));
                     try {
                     return $query->getResult();
                } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
                }
    }
   
}
