<?php

namespace LoveThatFit\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RetailerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetailerUserRepository extends EntityRepository
{
    public function getRetaielerUserByRetailer($retailer)
    {
        $query = $this->getEntityManager()
                    ->createQuery("SELECT r,ru FROM LoveThatFitAdminBundle:RetailerUser ru
                    JOIN ru.retailer r   
                    WHERE ru.retailer =:retailer")
                   ->setParameters(array('retailer' => $retailer));
                     try {
                     return $query->getResult();
                } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
                }
    }
}
