<?php

namespace LoveThatFit\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SaveLookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaveLookRepository extends EntityRepository
{
    public function getAllUserSaveLooks($user_id)
    {
        $query = $this->getEntityManager()
            ->createQuery("
                select sli,sl,i FROM LoveThatFitAdminBundle:SaveLook sl 
                 join sl.users u
                 join sl.save_look_item sli
                 join sli.items i
                 WHERE
                  u.id = :id
                ")->setParameters(array('id' => $user_id));

        try {
            // echo $query->getSQL();
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
