<?php

namespace LoveThatFit\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShopLookProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopLookProductRepository extends EntityRepository
{

    public function getShopLookProductsById($shoplook_id)
    {
        $shopProductTableName = $this->getEntityManager()->getClassMetadata('LoveThatFitAdminBundle:ShopLookProduct')->getTableName();
        $sql = "select * from shop_look_product sp
        where sp.shop_look_id = $shoplook_id";

        //set parameters
        $query = $this->getEntityManager()->getConnection()
            ->prepare($sql);
        $query->execute();
        $result_query = $query->fetchAll();
        return $result_query;
    }
}
