<?php

namespace LoveThatFit\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SizeChartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyQuestionRepository extends EntityRepository {

    public function findlistAllQuestion($page_number = 0, $limit = 0, $sort = 'id')
    {
        if ($page_number <= 0 || $limit <= 0) {
            $query = $this->getEntityManager()
                    ->createQuery('SELECT sq FROM LoveThatFitAdminBundle:SurveyQuestion sq ORDER BY sq.' . $sort . ' ASC');
        } else {
            $query = $this->getEntityManager()
                    ->createQuery('SELECT sq FROM LoveThatFitAdminBundle:SurveyQuestion sq ORDER BY sq.' . $sort . ' ASC')
                    ->setFirstResult($limit * ($page_number - 1))
                    ->setMaxResults($limit);
        }
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return "null";
        }
    }
    
    public function countAllRecord()
    {
        $total_record = $this->getEntityManager()
                ->createQuery('SELECT sq FROM LoveThatFitAdminBundle:SurveyQuestion sq');
        try {
            return $total_record->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
