<?php

namespace LoveThatFit\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SurveyUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyUserRepository extends EntityRepository
{
    public function findSurveyByUser($user) {
            $query = $this->getEntityManager()
                        ->createQuery("
     SELECT su,lu FROM LoveThatFitAdminBundle:SurveyUser su     
     JOIN su.user lu
     WHERE     
     su.user=:user"  )->setParameters(array('user'=>$user)) ;
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
