<?php

namespace LoveThatFit\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SurveyAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyAnswerRepository extends EntityRepository
{
    public function findlistAllQuestion($page_number = 0, $limit = 0, $sort = 'id')
    {
        if ($page_number <= 0 || $limit <= 0) {
            $query = $this->getEntityManager()
                    ->createQuery('SELECT sa FROM LoveThatFitAdminBundle:SurveyAnswer sq ORDER BY sa.' . $sort . ' ASC');
        } else {
            $query = $this->getEntityManager()
                    ->createQuery('SELECT sa FROM LoveThatFitAdminBundle:SurveyQuestion sa ORDER BY sa.' . $sort . ' ASC')
                    ->setFirstResult($limit * ($page_number - 1))
                    ->setMaxResults($limit);
        }
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return "null";
        }
    }
    
    public function countAllRecord()
    {
        $total_record = $this->getEntityManager()
                ->createQuery('SELECT sa FROM LoveThatFitAdminBundle:SurveyAnswer s');
        try {
            return $total_record->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    public function findOneByName($answer) {
        $query = $this->getEntityManager()
                        ->createQuery("SELECT sa FROM LoveThatFitAdminBundle:SurveyAnswer sa     
                                WHERE sa.answer=:answer")
                        ->setParameters(array('answer' => $answer));
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    public function findOneById($id) {
        $query = $this->getEntityManager()
                        ->createQuery("SELECT sa FROM LoveThatFitAdminBundle:SurveyAnswer sa     
                                WHERE sa.id=:id")
                        ->setParameters(array('id' => $id));
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }   
    
}
