parameters:
#    love_that_fit_support.example.class: LoveThatFit\SupportBundle\Example

services:
     kernel.listener.accessDenied:
        class: LoveThatFit\SupportBundle\Component\Event\AccessDeniedListener
        tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onAccessDeniedException }
            
     support.helper.supporttasklog:
        class: LoveThatFit\SupportBundle\DependencyInjection\SupportTaskLogHelper
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: LoveThatFit\SupportBundle\Entity\SupportTaskLog
            container: "@service_container"