
admin_fit_model_specs_index:
    pattern:  /admin/fit_model_specs/index
    defaults: { _controller: LoveThatFitAdminBundle:FitModelSpecs:index }

admin_fit_model_specs_create_new:
    pattern:  /admin/fit_model_specs/create_new
    defaults: { _controller: LoveThatFitAdminBundle:FitModelSpecs:createNew }

admin_fit_model_specs_save:    
    pattern:  /admin/fit_model_specs/save
    defaults: { _controller: LoveThatFitAdminBundle:FitModelSpecs:save } 
    
admin_fit_model_specs_show:
    pattern:  /admin/fit_model_specs/{id}/show
    defaults: { _controller: LoveThatFitAdminBundle:FitModelSpecs:show }
    