parameters:
#    cs_start.example.class: Cs\StartBundle\Example

services:
#    cs_start.example:
#        class: %cs_start.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
