<?php

namespace LoveThatFit\ProductIntakeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FitModelMeasurementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FitModelMeasurementRepository extends EntityRepository
{
	
 public function getArray() {
     $query = $this->getEntityManager()
                    ->createQuery('SELECT * FROM LoveThatFitAdminBundle:FitModelMeasurement');
  try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return "null";
        }   
 }

}
