parameters:
#    love_that_fit_shopify.example.class: LoveThatFit\ShopifyBundle\Example

services:
     shopify.helper:
        class: LoveThatFit\ShopifyBundle\DependencyInjection\ShopifyHelper
        arguments:
            container: "@service_container"
      
     shopifylib.helper:
        class: LoveThatFit\ShopifyBundle\DependencyInjection\ShopifyLibHelper    
        arguments:
            container: "@service_container"